#!/bin/bash
set -e

# GhidRift Docker Entrypoint Script
# This script provides a clean interface to GhidRift functionality within the container

# Default to the working directory mounted by the user
cd /workdir

# Function to display help
show_help() {
    cat << EOF
GhidRift Docker Container

Usage:
  docker run ghidrift/analyzer [COMMAND] [OPTIONS]

Commands:
  extract <binary>              Complete analysis: extract metadata + generate FIDB/BSIM signatures (default: both)
  analyze <metadata.json>       Generate FunctionID/BSIM signatures from existing metadata (default: both)
  full <binary>                 Alias for 'extract' (complete analysis pipeline)
  
  # Direct CLI access
  cli <args>                    Run ghidrift-cli directly with arguments
  ghidra                        Launch Ghidra GUI (requires X11 forwarding)
  shell                         Start interactive shell in container

Options for extract/analyze/full:
  --fid                         Generate ONLY FunctionID signatures
  --bsim                        Generate ONLY BSIM signatures  
  --verbose                     Enable verbose logging
  
Note: If no --fid or --bsim flags are provided, both signature types are generated by default.

Examples:
  # Complete analysis with both FIDB and BSIM signatures (default)
  docker run -v \$(pwd):/workdir ghidrift/analyzer extract my_rust_binary

  # Generate only FunctionID signatures from existing metadata
  docker run -v \$(pwd):/workdir ghidrift/analyzer analyze metadata.json --fid
  
  # Generate only BSIM signatures from existing metadata
  docker run -v \$(pwd):/workdir ghidrift/analyzer analyze metadata.json --bsim

  # Complete analysis with both signatures (same as no flags)
  docker run -v \$(pwd):/workdir ghidrift/analyzer full my_rust_binary --fid --bsim

  # Launch interactive shell for debugging
  docker run -it -v \$(pwd):/workdir ghidrift/analyzer shell

Environment Variables:
  GHIDRA_INSTALL_DIR           Path to Ghidra installation (set automatically)
  RUSTUP_HOME                  Rustup home directory (isolated in container)
  CARGO_HOME                   Cargo home directory (isolated in container)
EOF
}

# Function to determine default signature flags if none provided
get_default_flags() {
    local args=("$@")
    local has_fid=false
    local has_bsim=false
    
    # Check if --fid or --bsim flags are explicitly provided
    for arg in "${args[@]}"; do
        if [[ "$arg" == "--fid" ]]; then
            has_fid=true
        elif [[ "$arg" == "--bsim" ]]; then
            has_bsim=true
        fi
    done
    
    # If neither flag is provided, default to both
    if [[ "$has_fid" == false && "$has_bsim" == false ]]; then
        echo "--fid --bsim"
    else
        echo ""  # Use provided flags only
    fi
}

# Function to extract metadata and generate signatures from binary (complete pipeline)
extract_metadata() {
    local input_binary="$1"
    shift  # Remove first argument, rest are options
    
    if [[ ! -f "$input_binary" ]]; then
        echo "Error: Binary file '$input_binary' not found" >&2
        exit 1
    fi
    
    # Copy binary into container's working space
    local binary_name=$(basename "$input_binary")
    local container_binary="/tmp/analysis/$binary_name"
    # GhidRift_ExtractMetadata.java strips extension and creates {base_name}_metadata.json
    local base_name="${binary_name%.*}"  # Remove extension
    local container_metadata="/tmp/analysis/${base_name}_metadata.json"
    
    echo "Copying binary into container: $input_binary -> $container_binary"
    mkdir -p /tmp/analysis
    cp "$input_binary" "$container_binary"
    
    echo "Extracting metadata from '$container_binary'..."
    echo "Container metadata will be saved to '$container_metadata'"
    
    # Debug: Show Java version and environment  
    echo "Debug: Java version:"
    java -version
    echo "Debug: JAVA_HOME=$JAVA_HOME"
    echo "Debug: GHIDRA_INSTALL_DIR=$GHIDRA_INSTALL_DIR"
    
    # Create necessary directories
    mkdir -p /tmp/ghidra_projects
    
    # Run Ghidra headless analysis with metadata extraction
    echo "Extracting Rust metadata using GhidRift_ExtractMetadata.java..."
    echo "Debug: Available scripts in Ghidra directory:"
    ls -la $GHIDRA_INSTALL_DIR/Ghidra/Features/Base/ghidra_scripts/GhidRift_*.java
    
    # Set minimal Java options for container compatibility
    export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8"
    
    $GHIDRA_INSTALL_DIR/support/analyzeHeadless \
        /tmp/ghidra_projects \
        "metadata_$(basename "$container_binary")" \
        -import "$container_binary" \
        -postScript GhidRift_ExtractMetadata.java \
        -deleteProject \
        -readOnly
        
    if [[ -f "$container_metadata" ]]; then
        echo "Metadata extraction completed: $container_metadata"
        
        # Determine signature flags (default to both --fid --bsim if none specified)
        local default_flags=$(get_default_flags "$@")
        local signature_flags="$default_flags $@"
        
        echo "Generating signatures with flags: $signature_flags"
        cd /tmp/analysis
        python3 /app/ghidrift/cli/main.py "$container_metadata" --output /tmp/analysis --verbose $signature_flags
        
        # Copy results back to mounted working directory
        echo "Copying results to mounted directory..."

        # Copy metadata file back to host
        if [[ -f "$container_metadata" ]]; then
            echo "Copying metadata file..."
            cp "$container_metadata" /workdir/
            chmod 666 "/workdir/$(basename "$container_metadata")" 2>/dev/null || true
        fi

        # Copy debug log file back to host
        if [[ -f "/tmp/analysis/ghidrift_debug.log" ]]; then
            echo "Copying debug log..."
            cp /tmp/analysis/ghidrift_debug.log /workdir/
            chmod 666 /workdir/ghidrift_debug.log 2>/dev/null || true
        fi

        # Copy BSIM database files (H2 database creates multiple files)
        # Look for any .bsim* files (naming pattern is {metadata_name}.bsim*)
        if compgen -G "/tmp/analysis/*.bsim*" > /dev/null; then
            echo "Copying BSIM database files..."
            cp /tmp/analysis/*.bsim* /workdir/ 2>/dev/null || true
            chmod 666 /workdir/*.bsim* 2>/dev/null || true
        fi

        # Copy FIDB signature files from FIDB directory to workdir root
        if [[ -d "/tmp/analysis/FIDB" ]]; then
            echo "Copying FIDB signature files..."
            cp /tmp/analysis/FIDB/*.fidb /workdir/ 2>/dev/null || true
            chmod 666 /workdir/*.fidb 2>/dev/null || true
        fi

        # Copy any other signature files not in FIDB directory
        for file in /tmp/analysis/*.fidb; do
            if [[ -f "$file" ]]; then
                echo "Copying $(basename "$file")..."
                cp "$file" /workdir/
                chmod 666 "/workdir/$(basename "$file")" 2>/dev/null || true
            fi
        done

        # Copy coff directory if it exists
        if [[ -d "/tmp/analysis/coff" ]]; then
            echo "Copying COFF object files..."
            cp -r /tmp/analysis/coff /workdir/
            chmod -R 755 /workdir/coff 2>/dev/null || true
        fi

        echo "Complete signature generation pipeline completed successfully!"
        echo "Results available in mounted directory:"
        ls -la /workdir/
    else
        echo "Error: Metadata extraction failed" >&2
        exit 1
    fi
}

# Function to analyze metadata and generate signatures
analyze_metadata() {
    local input_metadata="$1"
    shift  # Remove first argument, rest are options
    
    if [[ ! -f "$input_metadata" ]]; then
        echo "Error: Metadata file '$input_metadata' not found" >&2
        exit 1
    fi
    
    # Copy metadata into container's working space
    local metadata_name=$(basename "$input_metadata")
    local container_metadata="/tmp/analysis/$metadata_name"
    local output_dir=$(dirname "$input_metadata")
    
    echo "Copying metadata into container: $input_metadata -> $container_metadata"
    mkdir -p /tmp/analysis
    cp "$input_metadata" "$container_metadata"
    
    # Also copy any existing coff/ directory if it exists
    local input_coff_dir="$(dirname "$input_metadata")/coff"
    if [[ -d "$input_coff_dir" ]]; then
        echo "Copying existing coff directory into container"
        cp -r "$input_coff_dir" /tmp/analysis/
    fi
    
    echo "Analyzing metadata from '$container_metadata' within container..."
    
    # Run ghidrift-cli within container, output to container space
    cd /tmp/analysis
    python3 /app/ghidrift/cli/main.py "$container_metadata" --output /tmp/analysis "$@"
    
    # Copy results back out
    echo "Copying results back to host..."

    # Copy debug log file
    if [[ -f "/tmp/analysis/ghidrift_debug.log" ]]; then
        echo "Copying debug log to $output_dir/"
        cp /tmp/analysis/ghidrift_debug.log "$output_dir/"
        chmod 666 "$output_dir"/ghidrift_debug.log 2>/dev/null || true
    fi

    # Copy BSIM database files (H2 database creates multiple files)
    # Look for any .bsim* files (naming pattern is {metadata_name}.bsim*)
    if compgen -G "/tmp/analysis/*.bsim*" > /dev/null; then
        echo "Copying BSIM database files to $output_dir/"
        cp /tmp/analysis/*.bsim* "$output_dir/" 2>/dev/null || true
        chmod 666 "$output_dir"/*.bsim* 2>/dev/null || true
    fi

    # Copy FIDB signature files from FIDB directory to output root
    if [[ -d "/tmp/analysis/FIDB" ]]; then
        echo "Copying FIDB signature files to $output_dir/"
        cp /tmp/analysis/FIDB/*.fidb "$output_dir/" 2>/dev/null || true
        chmod 666 "$output_dir"/*.fidb 2>/dev/null || true
    fi

    # Copy any other generated files not in FIDB directory
    for file in /tmp/analysis/*.fidb; do
        if [[ -f "$file" ]]; then
            echo "Copying $(basename "$file") to $output_dir/"
            cp "$file" "$output_dir/"
            chmod 666 "$output_dir/$(basename "$file")" 2>/dev/null || true
        fi
    done
    
    echo "Analysis completed, results copied to $output_dir/"
}

# Function to run full analysis pipeline
full_analysis() {
    local input_binary="$1"
    shift  # Remove first argument, rest are options
    
    if [[ ! -f "$input_binary" ]]; then
        echo "Error: Binary file '$input_binary' not found" >&2
        exit 1
    fi
    
    local output_metadata="${input_binary%.bin}.json"
    output_metadata="${output_metadata%.exe}.json"
    
    echo "Running full analysis pipeline on '$input_binary'..."
    
    # Step 1: Extract metadata and generate signatures (copies binary in, processes, copies results out)
    extract_metadata "$input_binary" "$@"
    
    echo "Full analysis pipeline completed!"
    echo "Results available in: $(dirname "$input_binary")/"
}

# Function to launch Ghidra GUI (requires X11 forwarding)
launch_ghidra() {
    echo "Launching Ghidra GUI..."
    echo "Note: This requires X11 forwarding: docker run -e DISPLAY=\$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ghidrift/analyzer ghidra"
    $GHIDRA_INSTALL_DIR/ghidraRun
}

# Function to start interactive shell
start_shell() {
    echo "Starting interactive shell in GhidRift container..."
    echo "Available commands:"
    echo "  ghidrift-cli - Direct access to CLI"
    echo "  rustup - Rust toolchain manager" 
    echo "  cargo - Rust package manager"
    echo "  ghidraRun - Launch Ghidra GUI"
    echo ""
    exec /bin/bash
}

# Main command processing
case "${1:-help}" in
    help|--help|-h)
        show_help
        ;;
    extract)
        if [[ -z "$2" ]]; then
            echo "Error: Binary file argument required" >&2
            echo "Usage: extract <binary>" >&2
            exit 1
        fi
        shift  # Remove 'extract' command
        extract_metadata "$@"
        ;;
    analyze)
        if [[ -z "$2" ]]; then
            echo "Error: Metadata file argument required" >&2
            echo "Usage: analyze <metadata.json> [OPTIONS]" >&2
            exit 1
        fi
        shift  # Remove 'analyze' command
        analyze_metadata "$@"
        ;;
    full)
        if [[ -z "$2" ]]; then
            echo "Error: Binary file argument required" >&2
            echo "Usage: full <binary> [OPTIONS]" >&2
            exit 1
        fi
        shift  # Remove 'full' command
        full_analysis "$@"
        ;;
    cli)
        shift  # Remove 'cli' command
        python3 /app/ghidrift/cli/main.py "$@"
        ;;
    ghidra)
        launch_ghidra
        ;;
    shell)
        start_shell
        ;;
    *)
        echo "Unknown command: $1" >&2
        echo "Use 'help' to see available commands" >&2
        exit 1
        ;;
esac